# Generated by Django 6.0.4 on 2026-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='books/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
