# Generated by Django 6.0.5 on 2026-05-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_update_book_borrow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
